stages:      
  - build
  - deploy

build:
  stage: build
  tags:
    - budget
  before_script:
    - docker system prune --all --force
  script:
    - docker compose build --no-cache
  only:
    - main

deploy:
  stage: deploy
  tags:
    - budget
  before_script:
    - docker system prune --all --force
  script:
    - docker compose up -d
  only:
    - main



