FROM node:18.1.0 AS builder

WORKDIR /app

COPY package*.json ./


RUN npm install --force clean-node-modules

COPY . .

RUN npm run build

FROM node:18.1.0

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["npm", "run", "start:prod"]